
name: prisma
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - h5py=3.7.0
  - hdf5=1.12.2
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - numpy=1.24.1
  - pip=22.3.1
  - python=3.9.16
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - scipy=1.10.0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - json5=0.9.14
  - pip:
    - accelerate==0.25.0
    - av==11.0.0
    - basicsr==1.4.2
    - click==8.1.7
    - cython==0.29.33
    - decord==0.6.0
    - diffusers==0.24.0
    - icecream==2.1.3
    - mediapipe==0.10.9
    - opencv-contrib-python==4.8.1.78
    - opencv-python==4.8.1.78
    - pyyaml==6.0.1
    - rerun-sdk==0.11.0
    - snowy==0.0.9
    - timm==0.6.12
    - tqdm==4.64.1
    - transformers==4.36.2